server:
  port: 8080
spring:
  application:
    name: app-api
  profiles:
    group:
      "local": "core-local, messages"
      "beta": "core-beta, messages"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/message
    fallback-to-system-locale: true
    encoding: UTF-8
logging:
  config: classpath:logback-spring.xml
springdoc:
  default-produces-media-type: application/json
#  api-docs:
#    path: /api-docs
---
server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: local
springdoc:
  api-docs:
    path: "/api-docs"
---
server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: beta
springdoc:
  api-docs:
    path: "/api-docs"
---